const Data = {
    status: "success",
    items: [
      {
        id: 1,
        title: "Cable USB MICRO",
        price: 800,
        image: require('./imagenes/usb.png'),
        category: "Accesorios",
        cantidad: 1,
      },
      {
        id: 2,
        title: "Pendrive SanDisk 32GB",
        price: 2000,
        image: require('./imagenes/pendrive.png'),
        category: "Accesorios",
        cantidad: 1,
      },
      {
        id: 3,
        title: "Cable USB to MICRO",
        price: 400,
        image: require('./imagenes/usbtomicro.png'),
        category: "Accesorios",
        cantidad: 1,
    },
      {
        id: 4,
        title: "Cargador para Auto",
        price: 1400,
        image: require('./imagenes/cargadorauto.png'),
        category: "Accesorios",
        cantidad: 1,
    },
      {
        id: 5,
        title: "Parlante Inalámbrico",
        price: 3420,
        image: require('./imagenes/parlante.png'),
        category: "Accesorios",
        cantidad: 1,
    },
      {
        id: 6,
        title: "Joystick Xbox",
        price: 19400,
        image: require('./imagenes/xbox.png'),
        category: "Accesorios",
        cantidad: 1,
    },
      {
        id: 7,
        title: "Cable USB C",
        price: 1670,
        image: require('./imagenes/usb c.png'),
        category: "Accesorios",
        cantidad: 1,
    },
    {
      id: 8,
      title: "Cargador Portatil",
      price: 11400,
      image: require('./imagenes/cargadorportatil.png'),
      category: "Accesorios",
      cantidad: 1,
  },{
    id:9 ,
    title: "Parlantes 2.0",
    price: 6400,
    image: require('./imagenes/altavoces.png'),
    category: "Accesorios",
    cantidad: 1,
},
{
  id: 10,
  title: "Auriculares",
  price: 3400,
  image: require('./imagenes/auriculares.png'),
  category: "Accesorios",
  cantidad: 1,
},
{
  id: 11,
  title: "IMAC",
  price: 785400,
  image: require('./imagenes/imac.png'),
  category: "Computadoras",
  cantidad: 1,
},
{
  id: 12,
  title: "Teclado + Mouse",
  price: 4400,
  image: require('./imagenes/teclado.png'),
  category: "Accesorios",
  cantidad: 1,
},
{
  id: 13,
  title: "Router",
  price: 14400,
  image: require('./imagenes/router.png'),
  category: "Accesorios",
  cantidad: 1,
},
{
  id: 14,
  title: "Subwoofer",
  price: 413400,
  image: require('./imagenes/subwoofer.png'),
  category: "Equipos de Música",
  cantidad: 1,
},
{
  id: 15,
  title: "Parlates 5.1",
  price: 74400,
  image: require('./imagenes/parlante5.png'),
  category: "Accesorios",
  cantidad: 1,
},
{
  id: 12,
  title: "Joystick Playstation 4",
  price: 48500,
  image: require('./imagenes/play4.png'),
  category: "Accesorios",
  cantidad: 1,
},
    ],
  };
  
  export default Data;
  